# Generated by Django 4.2.6 on 2023-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
